//
//  Tasks.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.3
//

import Foundation
import UIKit
import AWSDynamoDB

class Tasks: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _taskId: String?
    var _description: String?
    var _initiator: String?
    var _location: Set<NSNumber>?
    
    class func dynamoDBTableName() -> String {

        return "taskking-mobilehub-640940818-Tasks"
    }
    
    class func hashKeyAttribute() -> String {

        return "_taskId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_taskId" : "taskId",
               "_description" : "description",
               "_initiator" : "initiator",
               "_location" : "location",
        ]
    }
}
